/**
 * Child module enums — must stay in sync with prisma/schema.prisma
 */

export enum ChildGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}

export enum ChildStatus {
  REGISTERED = 'REGISTERED',
  ACTIVE = 'ACTIVE',
  ADOPTED = 'ADOPTED',
  REUNITED_WITH_FAMILY = 'REUNITED_WITH_FAMILY',
  TRANSFERRED = 'TRANSFERRED',
  DECEASED = 'DECEASED',
  MISSING = 'MISSING',
  RUNAWAY = 'RUNAWAY',
}

export enum AdoptionStatus {
  NOT_INITIATED = 'NOT_INITIATED',
  ELIGIBLE = 'ELIGIBLE',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MATCHED = 'MATCHED',
  LEGAL_PROCESS = 'LEGAL_PROCESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD',
}

export enum HealthStatus {
  HEALTHY = 'HEALTHY',
  UNDER_TREATMENT = 'UNDER_TREATMENT',
  CRITICAL = 'CRITICAL',
  RECOVERING = 'RECOVERING',
  CHRONIC_CONDITION = 'CHRONIC_CONDITION',
  UNKNOWN = 'UNKNOWN',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  EXCUSED = 'EXCUSED',
  HOLIDAY = 'HOLIDAY',
  SICK_LEAVE = 'SICK_LEAVE',
}

export enum EducationLevel {
  NOT_ENROLLED = 'NOT_ENROLLED',
  PRE_SCHOOL = 'PRE_SCHOOL',
  PRIMARY = 'PRIMARY',
  MIDDLE = 'MIDDLE',
  SECONDARY = 'SECONDARY',
  HIGHER_SECONDARY = 'HIGHER_SECONDARY',
  VOCATIONAL = 'VOCATIONAL',
  COLLEGE = 'COLLEGE',
  GRADUATED = 'GRADUATED',
  SPECIAL_EDUCATION = 'SPECIAL_EDUCATION',
}

export enum BloodGroup {
  A_POSITIVE = 'A_POSITIVE',
  A_NEGATIVE = 'A_NEGATIVE',
  B_POSITIVE = 'B_POSITIVE',
  B_NEGATIVE = 'B_NEGATIVE',
  AB_POSITIVE = 'AB_POSITIVE',
  AB_NEGATIVE = 'AB_NEGATIVE',
  O_POSITIVE = 'O_POSITIVE',
  O_NEGATIVE = 'O_NEGATIVE',
  UNKNOWN = 'UNKNOWN',
}

export enum GuardianRelation {
  BIOLOGICAL_PARENT = 'BIOLOGICAL_PARENT',
  ADOPTIVE_PARENT = 'ADOPTIVE_PARENT',
  FOSTER_PARENT = 'FOSTER_PARENT',
  GRANDPARENT = 'GRANDPARENT',
  UNCLE_AUNT = 'UNCLE_AUNT',
  SIBLING = 'SIBLING',
  LEGAL_GUARDIAN = 'LEGAL_GUARDIAN',
  ORPHANAGE_STAFF = 'ORPHANAGE_STAFF',
  SOCIAL_WORKER = 'SOCIAL_WORKER',
  OTHER = 'OTHER',
}

export enum ChildDocumentType {
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  AADHAAR_CARD = 'AADHAAR_CARD',
  SCHOOL_CERTIFICATE = 'SCHOOL_CERTIFICATE',
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  VACCINATION_CARD = 'VACCINATION_CARD',
  COURT_ORDER = 'COURT_ORDER',
  SURRENDER_DEED = 'SURRENDER_DEED',
  POLICE_REPORT = 'POLICE_REPORT',
  PHOTO_ID = 'PHOTO_ID',
  RELINQUISHMENT_DEED = 'RELINQUISHMENT_DEED',
  ADOPTION_ORDER = 'ADOPTION_ORDER',
  OTHER = 'OTHER',
}

export enum MedicalConditionSeverity {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  CRITICAL = 'CRITICAL',
}

export enum BiometricType {
  FINGERPRINT = 'FINGERPRINT',
  FACE_RECOGNITION = 'FACE_RECOGNITION',
  IRIS_SCAN = 'IRIS_SCAN',
  VOICE_PRINT = 'VOICE_PRINT',
}

export enum AttendanceActivity {
  SCHOOL = 'school',
  MEALS = 'meals',
  THERAPY = 'therapy',
  RECREATION = 'recreation',
  MEDICAL = 'medical',
  VOCATIONAL = 'vocational',
  GENERAL = 'general',
}
