import { Injectable, Logger } from '@nestjs/common';
import { AlertSeverity, AlertStatus, AlertType } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

// ─────────────────────────────────────────────────────────────
// Payload for creating a programmatic alert from any service
// ─────────────────────────────────────────────────────────────
export interface TriggerAlertPayload {
  type: AlertType;
  severity: AlertSeverity;
  title: string;
  details?: string;
  childId?: string;
  parentId?: string;
  orphanageId?: string;
  sourceService?: string;
  /** Optional: user ID that triggered the alert (if known) */
  createdById?: string;
  metadata?: any;
}

@Injectable()
export class AlertsGenerationService {
  private readonly logger = new Logger(AlertsGenerationService.name);

  constructor(private readonly prisma: PrismaService) {}

  // ───────────────────────────────────────────────────────────
  // Core method — called by any service when a safety condition
  // is detected.  Deduplicates: will not create a duplicate OPEN
  // alert of the same type for the same entity within 24 hours.
  // ───────────────────────────────────────────────────────────
  async triggerAlert(payload: TriggerAlertPayload): Promise<void> {
    try {
      // Deduplication window: 24 hours
      const since = new Date(Date.now() - 24 * 60 * 60 * 1000);

      const existing = await this.prisma.alert.findFirst({
        where: {
          type: payload.type,
          status: { in: [AlertStatus.OPEN, AlertStatus.ACKNOWLEDGED, AlertStatus.IN_PROGRESS] },
          createdAt: { gte: since },
          // Match on entity — at least one must match when supplied
          ...(payload.childId ? { childId: payload.childId } : {}),
          ...(payload.parentId && !payload.childId ? { parentId: payload.parentId } : {}),
          ...(payload.orphanageId && !payload.childId ? { orphanageId: payload.orphanageId } : {}),
        },
      });

      if (existing) {
        this.logger.debug(
          `Skipping duplicate alert: type=${payload.type} childId=${payload.childId ?? 'none'} (existing: ${existing.id})`,
        );
        return;
      }

      await this.prisma.alert.create({
        data: {
          type: payload.type,
          severity: payload.severity,
          title: payload.title,
          details: payload.details,
          status: AlertStatus.OPEN,
          isAutoGenerated: true,
          sourceService: payload.sourceService,
          childId: payload.childId,
          parentId: payload.parentId,
          orphanageId: payload.orphanageId,
          createdById: payload.createdById,
          metadata: payload.metadata,
        },
      });

      this.logger.log(
        `Auto-generated alert: [${payload.severity}] ${payload.type} — "${payload.title}"`,
      );
    } catch (error) {
      // Alert generation must never crash the calling service
      this.logger.error(
        `Failed to generate alert (type=${payload.type}): ${(error as Error).message}`,
        (error as Error).stack,
      );
    }
  }

  // ───────────────────────────────────────────────────────────
  // ADOPTION_BLOCKED — called when an adoption is cancelled
  // ───────────────────────────────────────────────────────────
  async onAdoptionCancelled(
    childId: string,
    parentId: string,
    orphanageId: string | null,
    reason: string,
    actorId: string,
  ): Promise<void> {
    await this.triggerAlert({
      type: AlertType.ADOPTION_BLOCKED,
      severity: AlertSeverity.HIGH,
      title: 'Adoption cancelled — child welfare review required',
      details: `An adoption process was cancelled. Reason: ${reason}. Welfare officer should verify child's current status and re-assess adoption eligibility.`,
      childId,
      parentId,
      orphanageId: orphanageId ?? undefined,
      sourceService: 'AdoptionsService',
      createdById: actorId,
    });
  }

  // ───────────────────────────────────────────────────────────
  // HEALTH_CRITICAL — called when a child's health status is
  // set to CRITICAL or a critical medical report is filed
  // ───────────────────────────────────────────────────────────
  async onHealthCritical(
    childId: string,
    childName: string,
    orphanageId: string | null,
    details: string,
    actorId?: string,
  ): Promise<void> {
    await this.triggerAlert({
      type: AlertType.HEALTH_CRITICAL,
      severity: AlertSeverity.CRITICAL,
      title: `Critical health condition: ${childName}`,
      details,
      childId,
      orphanageId: orphanageId ?? undefined,
      sourceService: 'HealthMonitoringService',
      createdById: actorId,
    });
  }

  // ───────────────────────────────────────────────────────────
  // AI_RISK_SPIKE — called when an AI risk score is HIGH/CRITICAL
  // ───────────────────────────────────────────────────────────
  async onAiRiskSpike(
    childId: string,
    childName: string,
    orphanageId: string | null,
    riskLevel: string,
    score: number,
    actorId?: string,
  ): Promise<void> {
    const severity =
      riskLevel === 'CRITICAL' ? AlertSeverity.CRITICAL : AlertSeverity.HIGH;

    await this.triggerAlert({
      type: AlertType.AI_RISK_SPIKE,
      severity,
      title: `AI risk spike detected: ${childName} (${riskLevel})`,
      details: `AI welfare assessment returned a ${riskLevel} risk score of ${score}/100. Immediate review by a welfare officer is recommended.`,
      childId,
      orphanageId: orphanageId ?? undefined,
      sourceService: 'AIRiskScoringService',
      createdById: actorId,
    });
  }

  // ───────────────────────────────────────────────────────────
  // LOW_ATTENDANCE — called after recording attendance when the
  // 30-day attendance rate falls below the threshold
  // ───────────────────────────────────────────────────────────
  async onLowAttendance(
    childId: string,
    childName: string,
    orphanageId: string | null,
    attendancePercent: number,
    actorId?: string,
  ): Promise<void> {
    await this.triggerAlert({
      type: AlertType.LOW_ATTENDANCE,
      severity: attendancePercent < 60 ? AlertSeverity.HIGH : AlertSeverity.MEDIUM,
      title: `Low attendance: ${childName} (${attendancePercent}%)`,
      details: `${childName}'s attendance has dropped to ${attendancePercent}% over the last 30 days (threshold: 80%). A welfare officer should follow up to determine if there is an underlying welfare concern.`,
      childId,
      orphanageId: orphanageId ?? undefined,
      sourceService: 'AttendanceService',
      createdById: actorId,
    });
  }

  // ───────────────────────────────────────────────────────────
  // LICENSE_EXPIRED — called by a scheduled cron job or when
  // an orphanage license expiry is detected
  // ───────────────────────────────────────────────────────────
  async onLicenseExpired(
    orphanageId: string,
    orphanageName: string,
    licenseType: string,
    expiryDate: Date,
  ): Promise<void> {
    await this.triggerAlert({
      type: AlertType.LICENSE_EXPIRED,
      severity: AlertSeverity.HIGH,
      title: `License expired: ${orphanageName} — ${licenseType}`,
      details: `The ${licenseType} license for ${orphanageName} expired on ${expiryDate.toLocaleDateString('en-IN')}. Immediate renewal is required to maintain compliance and operating status.`,
      orphanageId,
      sourceService: 'OrphanageComplianceService',
    });
  }

  // ───────────────────────────────────────────────────────────
  // WELFARE_SESSION_OVERDUE — called when a welfare session was
  // scheduled but not completed within the expected window
  // ───────────────────────────────────────────────────────────
  async onWelfareSessionOverdue(
    childId: string,
    childName: string,
    orphanageId: string | null,
    scheduledAt: Date,
  ): Promise<void> {
    await this.triggerAlert({
      type: AlertType.WELFARE_SESSION_OVERDUE,
      severity: AlertSeverity.MEDIUM,
      title: `Welfare session overdue: ${childName}`,
      details: `A welfare session for ${childName} was scheduled on ${scheduledAt.toLocaleDateString('en-IN')} but has not been completed. Please arrange a follow-up session immediately.`,
      childId,
      orphanageId: orphanageId ?? undefined,
      sourceService: 'WelfareSessionService',
    });
  }
}
