import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { AlertSeverity, AlertType } from '@prisma/client';
import { IsEnum, IsNotEmpty, IsOptional, IsString, IsUUID, IsBoolean } from 'class-validator';

export class CreateAlertDto {
  @ApiProperty({ enum: AlertType, description: 'The type of alert being raised' })
  @IsEnum(AlertType)
  type: AlertType;

  @ApiProperty({ enum: AlertSeverity, description: 'Severity level of the alert' })
  @IsEnum(AlertSeverity)
  severity: AlertSeverity;

  @ApiProperty({ description: 'Short descriptive title for the alert', example: 'Critical health condition detected' })
  @IsString()
  @IsNotEmpty()
  title: string;

  @ApiPropertyOptional({ description: 'Detailed description of the alert' })
  @IsOptional()
  @IsString()
  details?: string;

  @ApiPropertyOptional({ description: 'ID of the child this alert relates to' })
  @IsOptional()
  @IsUUID()
  childId?: string;

  @ApiPropertyOptional({ description: 'ID of the parent this alert relates to' })
  @IsOptional()
  @IsUUID()
  parentId?: string;

  @ApiPropertyOptional({ description: 'ID of the orphanage this alert relates to' })
  @IsOptional()
  @IsUUID()
  orphanageId?: string;

  @ApiPropertyOptional({ description: 'Whether this alert was auto-generated by the system', default: false })
  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;

  @ApiPropertyOptional({ description: 'The service that generated this alert', example: 'AdoptionService' })
  @IsOptional()
  @IsString()
  sourceService?: string;
}
