/**
 * All Parent-module enums.
 * Must stay in sync with the Prisma schema enums.
 */

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  SEPARATED = 'SEPARATED',
}

export enum EmploymentType {
  EMPLOYED_FULL_TIME = 'EMPLOYED_FULL_TIME',
  EMPLOYED_PART_TIME = 'EMPLOYED_PART_TIME',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  UNEMPLOYED = 'UNEMPLOYED',
  RETIRED = 'RETIRED',
  STUDENT = 'STUDENT',
}

export enum IncomeRange {
  BELOW_10K = 'BELOW_10K',
  RANGE_10K_25K = 'RANGE_10K_25K',
  RANGE_25K_50K = 'RANGE_25K_50K',
  RANGE_50K_100K = 'RANGE_50K_100K',
  ABOVE_100K = 'ABOVE_100K',
}

export enum ParentVerificationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DOCUMENTS_REQUIRED = 'DOCUMENTS_REQUIRED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum DocumentType {
  AADHAAR_CARD = 'AADHAAR_CARD',
  PAN_CARD = 'PAN_CARD',
  PASSPORT = 'PASSPORT',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  VOTER_ID = 'VOTER_ID',
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  MARRIAGE_CERTIFICATE = 'MARRIAGE_CERTIFICATE',
  INCOME_PROOF = 'INCOME_PROOF',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  BANK_STATEMENT = 'BANK_STATEMENT',
  ITR_DOCUMENT = 'ITR_DOCUMENT',
  EMPLOYMENT_LETTER = 'EMPLOYMENT_LETTER',
  NOC_CERTIFICATE = 'NOC_CERTIFICATE',
  POLICE_CLEARANCE = 'POLICE_CLEARANCE',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  PHOTO_ID = 'PHOTO_ID',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum AddressType {
  PERMANENT = 'PERMANENT',
  CURRENT = 'CURRENT',
  OFFICE = 'OFFICE',
}

export enum PoliceVerificationStatus {
  NOT_INITIATED = 'NOT_INITIATED',
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  CLEARED = 'CLEARED',
  FLAGGED = 'FLAGGED',
  REJECTED = 'REJECTED',
}

export enum RelationshipType {
  SPOUSE = 'SPOUSE',
  CHILD = 'CHILD',
  PARENT = 'PARENT',
  SIBLING = 'SIBLING',
  GRANDPARENT = 'GRANDPARENT',
  UNCLE_AUNT = 'UNCLE_AUNT',
  GUARDIAN = 'GUARDIAN',
  OTHER = 'OTHER',
}

export enum TrustScoreEvent {
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  POLICE_CLEARED = 'POLICE_CLEARED',
  POLICE_FLAGGED = 'POLICE_FLAGGED',
  INCOME_VERIFIED = 'INCOME_VERIFIED',
  ADDRESS_VERIFIED = 'ADDRESS_VERIFIED',
  INTERVIEW_PASSED = 'INTERVIEW_PASSED',
  INTERVIEW_FAILED = 'INTERVIEW_FAILED',
  REFERENCE_VERIFIED = 'REFERENCE_VERIFIED',
  PREVIOUS_ADOPTION = 'PREVIOUS_ADOPTION',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
}

export enum HouseOwnership {
  OWNED = 'OWNED',
  RENTED = 'RENTED',
  LEASED = 'LEASED',
  FAMILY_OWNED = 'FAMILY_OWNED',
}

export enum KycStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RE_UPLOAD_REQUIRED = 'RE_UPLOAD_REQUIRED',
}

export enum ChildGenderPreference {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  ANY = 'ANY',
}
