import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../../prisma/prisma.service';
import { ChildRegistrationNotificationService } from '../../notifications/child-registration-notification.service';
import { WellnessClassification } from '../enums/wellness-classification.enum';
import { RawEmotion } from '../enums/raw-emotion.enum';
import { AlertType, AlertSeverity } from '@prisma/client';

@Injectable()
export class WellnessAlertGeneratorService {
  private readonly logger = new Logger(WellnessAlertGeneratorService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly notificationService: ChildRegistrationNotificationService
  ) {}

  /**
   * Evaluates if a wellness alert should be generated and stored in Prisma.
   * Prevents false positive alerts from single isolated low-confidence predictions.
   */
  async evaluateAndGenerateAlert(params: {
    childId: string;
    childCode: string;
    childName: string;
    orphanageId?: string;
    orphanageName: string;
    wellnessScore: number;
    classification: WellnessClassification;
    primaryEmotion: RawEmotion;
    confidenceScore: number;
    persistentNegativePattern: boolean;
  }): Promise<{ alertTriggered: boolean; alertId?: string }> {
    const {
      childId,
      childCode,
      childName,
      orphanageId,
      orphanageName,
      wellnessScore,
      classification,
      primaryEmotion,
      confidenceScore,
      persistentNegativePattern,
    } = params;

    // Rule 1: Do NOT trigger alert on low-confidence predictions (<75%)
    if (confidenceScore < 75) {
      this.logger.debug(
        `Skipped alert generation for child ${childCode}: confidence ${confidenceScore}% below 75% threshold.`
      );
      return { alertTriggered: false };
    }

    // Rule 2: Trigger alert ONLY if score < 50 (NEEDS_ATTENTION) OR persistent multi-day pattern exists
    const shouldAlert = classification === WellnessClassification.NEEDS_ATTENTION || persistentNegativePattern;

    if (!shouldAlert) {
      return { alertTriggered: false };
    }

    const title = 'Wellness Alert: Needs Attention';
    const details = `Child ${childName} (${childCode}) classified as ${classification}. Daily Score: ${wellnessScore}/100. Primary Emotion: ${primaryEmotion} (${confidenceScore}% conf). ${
      persistentNegativePattern ? 'Multi-day concerning trend detected.' : ''
    }`;

    // Create Alert record in Prisma
    const alertRecord = await this.prisma.alert.create({
      data: {
        type: AlertType.AI_RISK_SPIKE,
        severity: AlertSeverity.HIGH,
        title,
        details,
        childId,
        orphanageId: orphanageId || null,
        isAutoGenerated: true,
        sourceService: 'ChildWellnessService',
        metadata: {
          wellnessScore,
          classification,
          primaryEmotion,
          confidenceScore,
          persistentNegativePattern,
        },
      },
    });

    this.logger.warn(`Generated Wellness Alert #${alertRecord.id} for child ${childCode} (${childName})`);

    // Trigger Admin Notification
    this.notificationService.notifyAdminsOnRegistration({
      childName: `${childName} (Needs Attention - Score ${wellnessScore})`,
      childCode: `WELLNESS-ALERT-${childCode}`,
      orphanageName,
      childId,
    });

    return {
      alertTriggered: true,
      alertId: alertRecord.id,
    };
  }
}
